apiVersion: v1
kind: Service
metadata:
  name: f1-app-service
spec:
  selector:
    app: f1-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 6000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-app
spec:
  selector:
    matchLabels:
      app: f1-app
  replicas: 4
  template:
    metadata:
      labels:
        app: f1-app
    spec:
      containers:
      - name: f1-app
        image: f1-app:v1.1
        imagePullPolicy: Never
        ports:
        - containerPort: 6000